### ISSUE TITLE
1.1.0 Roadmap

### ISSUE THREAD

**Issue by WeihanLi** [OpenReservation/ReservationServer#38]
- [x] Built-In IoC
- [x] Built-In AOP
- [x] Built-In Dapper
- [x] Built-In Repository
- [x] Built-In Logging
- [x] Built-In TOTP implement
- [x] Built-In EventBus
- [x] Built-In Cron
- [x] Built-In PipelineBuilder
- [ ] And More ...
